version: '3.8'
services:
  db:
    image: tugastst/farhan015
    container_name: mydocker
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD: 1234
    networks:
      - dockerflaskpython
    volumes:
      - /var/lib/mysql:/etc/mysql

  flask:
    image: tugaststflask/farhan015
    container_name: flask
    ports:
      - "80:80"
    networks:
      - dockerflaskpython
    depends_on:
      - db
      
networks: 
  tst-docker:
    name: dockerflaskpython
