version: '3.8'

services:
  db:
    image: tugastst/farhan015
    container_name: mydocker
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=userlogin
      - MYSQL_USER=farhan01
      - MYSQL_PASSWORD=farhan2001
    # networks:
    #   - dockerflaskpython
    volumes:
      - /etc/mysql:/docker-entrypoint-initdb.d

  flask:
    image: tugaststflask/farhan015
    container_name: flask
    ports:
      - "80:80"
    # networks:
    #   - dockerflaskpython
    depends_on:
      - db

# networks: 
#   docker_flaskPython:
#     name: dockerflaskpython
    
